{"NeoPixelEffects": {
  "strips":[
    {
      "pin" : "6",
      "leds" : "300",
      "frequence" : "800",
      "type" : "NEO_GRB",
      "loop" : [
        {
          "type" : "EffectRainbow",
          "steps" : "155",
          "delay" : "1",
          "colors" : [
            {
              "red" : "255",
              "green" : "0",
              "blue" : "0",
              "white" : "0"
            },
            {
              "red" : "0",
              "green" : "255",
              "blue" : "0",
              "white" : "0"
            }
          ],
          "options" : [
            {
              "name" : "rainbowlen",
              "value" : "300"
            },
            {
              "name" : "toLeft",
              "value" : "true"
            }
          ]
        },
        {
          "type" : "EffectFade",
          "steps" : "1000",
          "delay" : "1",
          "colors" : [
            {
              "red" : "255",
              "green" : "0",
              "blue" : "0",
              "white" : "0"
            },
            {
              "red" : "0",
              "green" : "0",
              "blue" : "0",
              "white" : "0"
            }
          ],
          "options" : [
            {
              "name" : "duration",
              "value" : "1000"
            },
            {
              "name" : "every",
              "value" : "1"
            }
          ]
        },
        {
          "type" : "EffectFade",
          "steps" : "1000",
          "delay" : "1",
          "colors" : [
            {
              "red" : "0",
              "green" : "255",
              "blue" : "0",
              "white" : "0"
            },
            {
              "red" : "255",
              "green" : "255",
              "blue" : "255",
              "white" : "0"
            }
          ],
          "options" : [
            {
              "name" : "duration",
              "value" : "1000"
            },
            {
              "name" : "every",
              "value" : "1"
            }
          ]
        }
      ]
    }
  ]
}
}